import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const validateOnly = process.argv.includes('--validate-only');
const root = process.cwd();
const inputPath = resolve(root, 'tokens.json');
const tokens = JSON.parse(readFileSync(inputPath, 'utf8'));

const requiredGroups = ['color', 'spacing', 'radius', 'elevation', 'typography'];
for (const group of requiredGroups) {
  if (!tokens[group]) {
    throw new Error(`Missing required token group: ${group}`);
  }
}

const colorNames = ['primary', 'secondary', 'success', 'warning', 'danger'];
for (const name of colorNames) {
  const token = tokens.color[name];
  if (!token?.light || !token?.dark) {
    throw new Error(`Color token ${name} must define light/dark values`);
  }
}

if (validateOnly) {
  console.log('Token schema validation passed.');
  process.exit(0);
}

const cssVars = [];
const darkVars = [];
const scssVars = [];
const tsColors = {};

for (const [name, token] of Object.entries(tokens.color)) {
  cssVars.push(`  --ds-color-${name}: ${token.light};`);
  darkVars.push(`  --ds-color-${name}: ${token.dark};`);
  scssVars.push(`$ds-color-${name}: ${token.light};`);
  tsColors[name] = token;
}

for (const [name, token] of Object.entries(tokens.spacing)) {
  cssVars.push(`  --ds-spacing-${name}: ${token.$value};`);
  scssVars.push(`$ds-spacing-${name}: ${token.$value};`);
}
for (const [name, token] of Object.entries(tokens.radius)) {
  cssVars.push(`  --ds-radius-${name}: ${token.$value};`);
  scssVars.push(`$ds-radius-${name}: ${token.$value};`);
}
for (const [name, token] of Object.entries(tokens.elevation)) {
  cssVars.push(`  --ds-elevation-${name}: ${token.$value};`);
}
for (const [name, token] of Object.entries(tokens.typography.size)) {
  cssVars.push(`  --ds-font-size-${name}: ${token.$value};`);
}
for (const [name, token] of Object.entries(tokens.typography.weight)) {
  cssVars.push(`  --ds-font-weight-${name}: ${token.$value};`);
}
cssVars.push(`  --ds-font-family-base: ${tokens.typography.fontFamily.$value};`);
scssVars.push(`$font-family-base: ${tokens.typography.fontFamily.$value};`);
scssVars.push(`$primary: ${tokens.color.primary.light};`);
scssVars.push(`$secondary: ${tokens.color.secondary.light};`);
scssVars.push(`$success: ${tokens.color.success.light};`);
scssVars.push(`$warning: ${tokens.color.warning.light};`);
scssVars.push(`$danger: ${tokens.color.danger.light};`);

writeFileSync(resolve(root, 'libs/tokens/src/tokens.css'), `:root {\n${cssVars.join('\n')}\n}\n\n[data-theme="dark"] {\n${darkVars.join('\n')}\n}\n`);
writeFileSync(resolve(root, 'libs/tokens/src/tokens.scss'), `// Generated by token compiler.\n${scssVars.join('\n')}\n`);
writeFileSync(resolve(root, 'libs/tokens/src/tokens.ts'), `// Generated by token compiler.\nexport const dsTokens = ${JSON.stringify(tokens, null, 2)} as const;\nexport type DsTokens = typeof dsTokens;\n`);
writeFileSync(resolve(root, 'libs/tokens/src/tokens.figma.json'), JSON.stringify({
  collections: [{
    name: 'NG BT Design Tokens',
    modes: tokens.modes,
    variables: tokens
  }]
}, null, 2));

console.log('Token artifacts generated successfully.');
