// Generated by token compiler.
export const dsTokens = {
  "$schema": "https://www.designtokens.org/tr/drafts/format/draft-2023-10/schema.json",
  "modes": [
    "light",
    "dark"
  ],
  "color": {
    "primary": {
      "$type": "color",
      "light": "#0d6efd",
      "dark": "#6ea8fe"
    },
    "secondary": {
      "$type": "color",
      "light": "#6c757d",
      "dark": "#adb5bd"
    },
    "success": {
      "$type": "color",
      "light": "#198754",
      "dark": "#75b798"
    },
    "warning": {
      "$type": "color",
      "light": "#ffc107",
      "dark": "#ffda6a"
    },
    "danger": {
      "$type": "color",
      "light": "#dc3545",
      "dark": "#ea868f"
    }
  },
  "spacing": {
    "xs": {
      "$type": "dimension",
      "$value": "0.25rem"
    },
    "sm": {
      "$type": "dimension",
      "$value": "0.5rem"
    },
    "md": {
      "$type": "dimension",
      "$value": "1rem"
    },
    "lg": {
      "$type": "dimension",
      "$value": "1.5rem"
    },
    "xl": {
      "$type": "dimension",
      "$value": "2rem"
    }
  },
  "radius": {
    "sm": {
      "$type": "dimension",
      "$value": "0.25rem"
    },
    "md": {
      "$type": "dimension",
      "$value": "0.5rem"
    },
    "lg": {
      "$type": "dimension",
      "$value": "0.75rem"
    }
  },
  "elevation": {
    "sm": {
      "$type": "shadow",
      "$value": "0 1px 2px rgba(0,0,0,0.08)"
    },
    "md": {
      "$type": "shadow",
      "$value": "0 3px 6px rgba(0,0,0,0.12)"
    },
    "lg": {
      "$type": "shadow",
      "$value": "0 8px 16px rgba(0,0,0,0.16)"
    }
  },
  "typography": {
    "fontFamily": {
      "$type": "fontFamily",
      "$value": "Inter, system-ui, sans-serif"
    },
    "size": {
      "sm": {
        "$type": "dimension",
        "$value": "0.875rem"
      },
      "md": {
        "$type": "dimension",
        "$value": "1rem"
      },
      "lg": {
        "$type": "dimension",
        "$value": "1.25rem"
      }
    },
    "weight": {
      "regular": {
        "$type": "fontWeight",
        "$value": 400
      },
      "semibold": {
        "$type": "fontWeight",
        "$value": 600
      },
      "bold": {
        "$type": "fontWeight",
        "$value": 700
      }
    }
  }
} as const;
export type DsTokens = typeof dsTokens;
